version: "3.9"
services:
  wiki-bot:
    build: .
    container_name: wiki-bot
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"  # leave empty if not using
    restart: unless-stopped
